### ISSUE TITLE
Flies on all versions of android up to version LOLLIPOP_MR1.

### ISSUE THREAD

**Issue by Zevsus** [hedzr/android-file-chooser#38]
If you enable .enableOptions (true) and and click on the open menu in the dialog with the addition and deletion of the folder crashes. Thanks for helping me solve the problem. 
Fatal Exception: java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to android.widget.FrameLayout
       at com.obsez.android.lib.filechooser.ChooserDialog$9$6.onClick(ChooserDialog.java:599)
       at android.view.View.performClick(View.java:4756)
       at android.view.View$PerformClick.run(View.java:19749)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5221)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by hedzr** [comment]
sorry for my delayed reply.
but i need more details.

**Comment by hedzr** [comment]
~~reviewing~~. i have run in android 5.1 emulator but can't reproduce your exception. it seems to work fine.
Okay, i got it in 5.0. i'm working...

**Comment by hedzr** [comment]
a new patch on `master` branch is ready. i hope it's solid.

try it from jitpack.io:

```gradle
implementation 'com.github.hedzr:android-file-chooser:master-SNAPSHOT'
# or
implementation 'com.github.hedzr:android-file-chooser:88fb3309ca'
```

sometimes you'd better [disable gradle cache](https://docs.gradle.org/current/userguide/introduction_dependency_management.html#changing-module-cache-control) for jitpack, add these lines into the root-level build.gradle:

```gradle
buildscript {
  configurations.all {
      resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
      resolutionStrategy.cacheDynamicVersionsFor 0, 'seconds'
  }
}
```

see also: https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html

**Comment by hedzr** [comment]
It's strongly recommended to retrieve v1.1.14 via jcenter.

```gradle
implementation 'com.obsez.android.lib.filechooser:filechooser:1.1.14'
```

or jitpack:

```gradle
//implementation 'com.github.hedzr:android-file-chooser:master-SNAPSHOT'
// or
implementation 'com.github.hedzr:android-file-chooser:d6aa2c4f1b'
```
