### ISSUE TITLE
Runtime Exception on Android 6 devices

### ISSUE THREAD

**Issue by ytheekshana** [hedzr/android-file-chooser#60]
Got a runtime exception only on Android 6 devices after 1.1.17 update

> Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=347, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.ytheekshana.deviceinfo/com.obsez.android.lib.filechooser.permissions.PermissionActivity}: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
    at android.app.ActivityThread.deliverResults(ActivityThread.java:5004)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:5047)
    at android.app.ActivityThread.access$1600(ActivityThread.java:229)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:7406)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

> Caused by android.util.AndroidRuntimeException: requestFeature() must be called before adding content
       at com.android.internal.policy.PhoneWindow.requestFeature(PhoneWindow.java:411)
       at com.android.internal.app.AlertController.installContent(AlertController.java:250)
       at android.app.AlertDialog.onCreate(AlertDialog.java:437)
       at android.app.Dialog.dispatchOnCreate(Dialog.java:733)
       at android.app.Dialog.show(Dialog.java:469)
       at com.obsez.android.lib.filechooser.ChooserDialog.showDialog(ChooserDialog.java:568)
       at com.obsez.android.lib.filechooser.ChooserDialog.access$000(ChooserDialog.java:65)
       at com.obsez.android.lib.filechooser.ChooserDialog$1.onPermissionGranted(ChooserDialog.java:604)
       at com.obsez.android.lib.filechooser.permissions.PermissionActivity.onRequestPermissionsResult(PermissionActivity.java:81)
       at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7291)
       at android.app.Activity.dispatchActivityResult(Activity.java:7169)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5000)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5047)
       at android.app.ActivityThread.access$1600(ActivityThread.java:229)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7406)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by hedzr** [comment]
hmmm, it's a bug.
fortunately, or unfortunately, it occurs just under android M: https://issuetracker.google.com/issues/37061719

they announced one or two workaround(s). it's not fit for me. but i tried to avoid it at the next commit. see my commit later.
And, there is another way to disable the exception: DON'T enable `displayPath` in your case. That means: call `.displayPath(false)`.

**Comment by hedzr** [comment]
if you like displayPath, retrieve the patch (8d6156f6d2, or 5257025c2d) by following jitpack doc:

https://jitpack.io/#hedzr/android-file-chooser/8d6156f6d2

**Comment by ytheekshana** [comment]
Ok. I'll call .displayPath(false) as I don't need the path displayed. 
Thanks

**Comment by Guiorgy** [comment]
hmm, I've been testing it on a Kitkat emulator, yet I am failing to replicate this exception

**Comment by ytheekshana** [comment]
> 
> 
> hmm, I've been testing it on a Kitkat emulator, yet I am failing to replicate this exception

Happened to me only on Android 6

**Comment by Guiorgy** [comment]
> fortunately, or unfortunately, it occurs just under android M

thought any api < 26? I'll check M then

edit: indeed, I got the error...

**Comment by hedzr** [comment]
the patch is a work around for M, and the operating expirences has not been break. i guess that's ok now.

**Comment by Guiorgy** [comment]
there is a simpler way to make it work though:
<pre lang="java">
if (_alertDialog != null && <b><i>_alertDialog.isShowing()</i></b> && _displayPath) { ...
</pre>
just need to check that **_alertDialog** is already showing.

**Comment by Guiorgy** [comment]
1.1.19 out, please confirm that the problem has been solved.

**Comment by omarman2** [comment]
omarman_2006a@hotmail.com

**Comment by kartik1225** [comment]
Is that issue is resolved? **If yes then how?**
