### ISSUE TITLE
error Theme.AppCompat theme

### ISSUE THREAD

**Issue by Kadanza** [hedzr/android-file-chooser#87]
error on final version 1.2.0

on 1.1.14 version work  normal

Phone Xiomi redmi 3s

java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

java.lang.RuntimeException: Unable to start activity ComponentInfo{org.kadance.ling.dev/com.obsez.android.lib.filechooser.permissions.PermissionActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2485)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2545)
        at android.app.ActivityThread.access$1100(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1396)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5601)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
     Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:696)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:659)
        at androidx.appcompat.app.AppCompatDelegateImpl.onPostCreate(AppCompatDelegateImpl.java:376)
        at androidx.appcompat.app.AppCompatActivity.onPostCreate(AppCompatActivity.java:118)
        at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1189)

**Comment by Guiorgy** [comment]
Could you try
```implementation 'com.github.hedzr:android-file-chooser:1.2.0-SNAPSHOT'```

**Comment by Kadanza** [comment]
> Could you try
> `implementation 'com.github.hedzr:android-file-chooser:1.2.0-SNAPSHOT'`

All the same

I got error 

  java.lang.RuntimeException: Unable to start activity 


ComponentInfo{org.kadance.ling.dev/com.obsez.android.lib.filechooser.permissions.PermissionActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

**Comment by Guiorgy** [comment]
Strange, the only theme we use internally is ```<style name="Theme.Transparent" parent="Theme.AppCompat.NoActionBar">``` which as you can see extends AppCompat.

Do you implement your own permission logic or use the built in one?
